repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: sort-simple-yaml
  - id: check-xml
  - id: check-merge-conflict
  - id: check-ast
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: fix-encoding-pragma
  - id: no-commit-to-branch
    args: [--branch, master]
ci:
  autofix_prs: false
