relativeURLs = true
languageCode = "en-us"
enableGitInfo = true

[author]
  name = "Lu√≠s Ferreira"

[markup]
  [markup.highlight]
      codeFences = true
      style = 'emacs'

[languages]
  [languages.en]
    title = "luis space"
    copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = -3
      [[languages.en.menu.main]]
        identifier = "tasks"
        name = "Tasks"
        url = "https://tasks.lsferreira.net"
        weight = -2
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = -1
      [[languages.en.menu.main]]
        identifier = "static-content"
        name = "Index"
        url = "/public"
        weight = 0
